# Generated by Django 5.1.2 on 2024-10-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shop_department',
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_dow', models.IntegerField()),
                ('order_hour_of_day', models.IntegerField()),
                ('eval_set', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('price_z', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopdepartment')),
            ],
            options={
                'db_table': 'shop_product',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderproduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_to_cart_order', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shoporder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopproduct')),
            ],
            options={
                'db_table': 'shop_order_product',
            },
        ),
    ]
