# Generated by Django 5.1.2 on 2024-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shop_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_dow', models.IntegerField()),
                ('order_hour_of_day', models.IntegerField()),
                ('eval_set', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shop_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopOrderproduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_to_cart_order', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_orderproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('price_z', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_product',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='department',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
